package db;
// Generated Jul 7, 2017 7:01:22 PM by Hibernate Tools 4.3.1



/**
 * Galerija generated by hbm2java
 */
public class Galerija  implements java.io.Serializable {


     private Integer idslika;
     private Sesija sesija;
     private String slika;

    public Galerija() {
    }

    public Galerija(Sesija sesija, String slika) {
       this.sesija = sesija;
       this.slika = slika;
    }
   
    public Integer getIdslika() {
        return this.idslika;
    }
    
    public void setIdslika(Integer idslika) {
        this.idslika = idslika;
    }
    public Sesija getSesija() {
        return this.sesija;
    }
    
    public void setSesija(Sesija sesija) {
        this.sesija = sesija;
    }
    public String getSlika() {
        return this.slika;
    }
    
    public void setSlika(String slika) {
        this.slika = slika;
    }




}


