package db;
// Generated Jul 7, 2017 7:01:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Konferencija generated by hbm2java
 */
public class Konferencija  implements java.io.Serializable {


     private Integer idkonf;
     private Korisnik korisnik;
     private Mesto mesto;
     private Oblast oblast;
     private String naziv;
     private Date datumOd;
     private Date datumDo;
     private String sifra;
     private Set prijavas = new HashSet(0);
     private Set sesijas = new HashSet(0);

    public Konferencija() {
    }

	
    public Konferencija(Korisnik korisnik, Mesto mesto, Oblast oblast, String sifra) {
        this.korisnik = korisnik;
        this.mesto = mesto;
        this.oblast = oblast;
        this.sifra = sifra;
    }
    public Konferencija(Korisnik korisnik, Mesto mesto, Oblast oblast, String naziv, Date datumOd, Date datumDo, String sifra, Set prijavas, Set sesijas) {
       this.korisnik = korisnik;
       this.mesto = mesto;
       this.oblast = oblast;
       this.naziv = naziv;
       this.datumOd = datumOd;
       this.datumDo = datumDo;
       this.sifra = sifra;
       this.prijavas = prijavas;
       this.sesijas = sesijas;
    }
   
    public Integer getIdkonf() {
        return this.idkonf;
    }
    
    public void setIdkonf(Integer idkonf) {
        this.idkonf = idkonf;
    }
    public Korisnik getKorisnik() {
        return this.korisnik;
    }
    
    public void setKorisnik(Korisnik korisnik) {
        this.korisnik = korisnik;
    }
    public Mesto getMesto() {
        return this.mesto;
    }
    
    public void setMesto(Mesto mesto) {
        this.mesto = mesto;
    }
    public Oblast getOblast() {
        return this.oblast;
    }
    
    public void setOblast(Oblast oblast) {
        this.oblast = oblast;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public Date getDatumOd() {
        return this.datumOd;
    }
    
    public void setDatumOd(Date datumOd) {
        this.datumOd = datumOd;
    }
    public Date getDatumDo() {
        return this.datumDo;
    }
    
    public void setDatumDo(Date datumDo) {
        this.datumDo = datumDo;
    }
    public String getSifra() {
        return this.sifra;
    }
    
    public void setSifra(String sifra) {
        this.sifra = sifra;
    }
    public Set getPrijavas() {
        return this.prijavas;
    }
    
    public void setPrijavas(Set prijavas) {
        this.prijavas = prijavas;
    }
    public Set getSesijas() {
        return this.sesijas;
    }
    
    public void setSesijas(Set sesijas) {
        this.sesijas = sesijas;
    }




}


