package db;
// Generated Jul 7, 2017 7:01:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Korisnik generated by hbm2java
 */
public class Korisnik  implements java.io.Serializable {


     private String username;
     private String lozinka;
     private String ime;
     private String prezime;
     private String email;
     private String institucija;
     private String pol;
     private String slika;
     private String majca;
     private String linkedin;
     private String tip;
     private Set predavanjesForAutor3 = new HashSet(0);
     private Set predavanjesForAutor4 = new HashSet(0);
     private Set predavanjesForAutor1 = new HashSet(0);
     private Set prijavas = new HashSet(0);
     private Set predavanjesForAutor2 = new HashSet(0);
     private Set porukasForPosiljalac = new HashSet(0);
     private Set porukasForPrimalac = new HashSet(0);
     private Set konferencijas = new HashSet(0);
     private Set prijavaPredavanjes = new HashSet(0);
     private Set komentars = new HashSet(0);

    public Korisnik() {
    }

	
    public Korisnik(String username, String lozinka, String tip) {
        this.username = username;
        this.lozinka = lozinka;
        this.tip = tip;
    }
    public Korisnik(String username, String lozinka, String ime, String prezime, String email, String institucija, String pol, String slika, String majca, String linkedin, String tip, Set predavanjesForAutor3, Set predavanjesForAutor4, Set predavanjesForAutor1, Set prijavas, Set predavanjesForAutor2, Set porukasForPosiljalac, Set porukasForPrimalac, Set konferencijas, Set prijavaPredavanjes, Set komentars) {
       this.username = username;
       this.lozinka = lozinka;
       this.ime = ime;
       this.prezime = prezime;
       this.email = email;
       this.institucija = institucija;
       this.pol = pol;
       this.slika = slika;
       this.majca = majca;
       this.linkedin = linkedin;
       this.tip = tip;
       this.predavanjesForAutor3 = predavanjesForAutor3;
       this.predavanjesForAutor4 = predavanjesForAutor4;
       this.predavanjesForAutor1 = predavanjesForAutor1;
       this.prijavas = prijavas;
       this.predavanjesForAutor2 = predavanjesForAutor2;
       this.porukasForPosiljalac = porukasForPosiljalac;
       this.porukasForPrimalac = porukasForPrimalac;
       this.konferencijas = konferencijas;
       this.prijavaPredavanjes = prijavaPredavanjes;
       this.komentars = komentars;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getLozinka() {
        return this.lozinka;
    }
    
    public void setLozinka(String lozinka) {
        this.lozinka = lozinka;
    }
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getInstitucija() {
        return this.institucija;
    }
    
    public void setInstitucija(String institucija) {
        this.institucija = institucija;
    }
    public String getPol() {
        return this.pol;
    }
    
    public void setPol(String pol) {
        this.pol = pol;
    }
    public String getSlika() {
        return this.slika;
    }
    
    public void setSlika(String slika) {
        this.slika = slika;
    }
    public String getMajca() {
        return this.majca;
    }
    
    public void setMajca(String majca) {
        this.majca = majca;
    }
    public String getLinkedin() {
        return this.linkedin;
    }
    
    public void setLinkedin(String linkedin) {
        this.linkedin = linkedin;
    }
    public String getTip() {
        return this.tip;
    }
    
    public void setTip(String tip) {
        this.tip = tip;
    }
    public Set getPredavanjesForAutor3() {
        return this.predavanjesForAutor3;
    }
    
    public void setPredavanjesForAutor3(Set predavanjesForAutor3) {
        this.predavanjesForAutor3 = predavanjesForAutor3;
    }
    public Set getPredavanjesForAutor4() {
        return this.predavanjesForAutor4;
    }
    
    public void setPredavanjesForAutor4(Set predavanjesForAutor4) {
        this.predavanjesForAutor4 = predavanjesForAutor4;
    }
    public Set getPredavanjesForAutor1() {
        return this.predavanjesForAutor1;
    }
    
    public void setPredavanjesForAutor1(Set predavanjesForAutor1) {
        this.predavanjesForAutor1 = predavanjesForAutor1;
    }
    public Set getPrijavas() {
        return this.prijavas;
    }
    
    public void setPrijavas(Set prijavas) {
        this.prijavas = prijavas;
    }
    public Set getPredavanjesForAutor2() {
        return this.predavanjesForAutor2;
    }
    
    public void setPredavanjesForAutor2(Set predavanjesForAutor2) {
        this.predavanjesForAutor2 = predavanjesForAutor2;
    }
    public Set getPorukasForPosiljalac() {
        return this.porukasForPosiljalac;
    }
    
    public void setPorukasForPosiljalac(Set porukasForPosiljalac) {
        this.porukasForPosiljalac = porukasForPosiljalac;
    }
    public Set getPorukasForPrimalac() {
        return this.porukasForPrimalac;
    }
    
    public void setPorukasForPrimalac(Set porukasForPrimalac) {
        this.porukasForPrimalac = porukasForPrimalac;
    }
    public Set getKonferencijas() {
        return this.konferencijas;
    }
    
    public void setKonferencijas(Set konferencijas) {
        this.konferencijas = konferencijas;
    }
    public Set getPrijavaPredavanjes() {
        return this.prijavaPredavanjes;
    }
    
    public void setPrijavaPredavanjes(Set prijavaPredavanjes) {
        this.prijavaPredavanjes = prijavaPredavanjes;
    }
    public Set getKomentars() {
        return this.komentars;
    }
    
    public void setKomentars(Set komentars) {
        this.komentars = komentars;
    }




}


