package db;
// Generated Jul 7, 2017 7:01:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Mesto generated by hbm2java
 */
public class Mesto  implements java.io.Serializable {


     private Integer idmesto;
     private String grad;
     private String drzava;
     private String lokacija;
     private Set konferencijas = new HashSet(0);
     private Set salas = new HashSet(0);

    public Mesto() {
    }

	
    public Mesto(String grad, String drzava, String lokacija) {
        this.grad = grad;
        this.drzava = drzava;
        this.lokacija = lokacija;
    }
    public Mesto(String grad, String drzava, String lokacija, Set konferencijas, Set salas) {
       this.grad = grad;
       this.drzava = drzava;
       this.lokacija = lokacija;
       this.konferencijas = konferencijas;
       this.salas = salas;
    }
   
    public Integer getIdmesto() {
        return this.idmesto;
    }
    
    public void setIdmesto(Integer idmesto) {
        this.idmesto = idmesto;
    }
    public String getGrad() {
        return this.grad;
    }
    
    public void setGrad(String grad) {
        this.grad = grad;
    }
    public String getDrzava() {
        return this.drzava;
    }
    
    public void setDrzava(String drzava) {
        this.drzava = drzava;
    }
    public String getLokacija() {
        return this.lokacija;
    }
    
    public void setLokacija(String lokacija) {
        this.lokacija = lokacija;
    }
    public Set getKonferencijas() {
        return this.konferencijas;
    }
    
    public void setKonferencijas(Set konferencijas) {
        this.konferencijas = konferencijas;
    }
    public Set getSalas() {
        return this.salas;
    }
    
    public void setSalas(Set salas) {
        this.salas = salas;
    }




}


