package db;
// Generated Jul 7, 2017 7:01:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Oblast generated by hbm2java
 */
public class Oblast  implements java.io.Serializable {


     private Integer idoblast;
     private String oblast;
     private Set konferencijas = new HashSet(0);

    public Oblast() {
    }

	
    public Oblast(String oblast) {
        this.oblast = oblast;
    }
    public Oblast(String oblast, Set konferencijas) {
       this.oblast = oblast;
       this.konferencijas = konferencijas;
    }
   
    public Integer getIdoblast() {
        return this.idoblast;
    }
    
    public void setIdoblast(Integer idoblast) {
        this.idoblast = idoblast;
    }
    public String getOblast() {
        return this.oblast;
    }
    
    public void setOblast(String oblast) {
        this.oblast = oblast;
    }
    public Set getKonferencijas() {
        return this.konferencijas;
    }
    
    public void setKonferencijas(Set konferencijas) {
        this.konferencijas = konferencijas;
    }




}


