package db;
// Generated Jul 7, 2017 7:01:22 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Poruka generated by hbm2java
 */
public class Poruka  implements java.io.Serializable {


     private Integer idporuka;
     private Korisnik korisnikByPosiljalac;
     private Korisnik korisnikByPrimalac;
     private Date datum;
     private String text;

    public Poruka() {
    }

    public Poruka(Korisnik korisnikByPosiljalac, Korisnik korisnikByPrimalac, Date datum, String text) {
       this.korisnikByPosiljalac = korisnikByPosiljalac;
       this.korisnikByPrimalac = korisnikByPrimalac;
       this.datum = datum;
       this.text = text;
    }
   
    public Integer getIdporuka() {
        return this.idporuka;
    }
    
    public void setIdporuka(Integer idporuka) {
        this.idporuka = idporuka;
    }
    public Korisnik getKorisnikByPosiljalac() {
        return this.korisnikByPosiljalac;
    }
    
    public void setKorisnikByPosiljalac(Korisnik korisnikByPosiljalac) {
        this.korisnikByPosiljalac = korisnikByPosiljalac;
    }
    public Korisnik getKorisnikByPrimalac() {
        return this.korisnikByPrimalac;
    }
    
    public void setKorisnikByPrimalac(Korisnik korisnikByPrimalac) {
        this.korisnikByPrimalac = korisnikByPrimalac;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }




}


