package db;
// Generated Jul 7, 2017 7:01:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Predavanje generated by hbm2java
 */
public class Predavanje  implements java.io.Serializable {


     private Integer idpred;
     private Korisnik korisnikByAutor3;
     private Korisnik korisnikByAutor4;
     private Korisnik korisnikByAutor1;
     private Korisnik korisnikByAutor2;
     private Sesija sesija;
     private String naslov;
     private Integer trajanje;
     private String tip;
     private Date pocetak;
     private Set komentars = new HashSet(0);

    public Predavanje() {
    }

	
    public Predavanje(Korisnik korisnikByAutor1, Sesija sesija, String naslov, String tip, Date pocetak) {
        this.korisnikByAutor1 = korisnikByAutor1;
        this.sesija = sesija;
        this.naslov = naslov;
        this.tip = tip;
        this.pocetak = pocetak;
    }
    public Predavanje(Korisnik korisnikByAutor3, Korisnik korisnikByAutor4, Korisnik korisnikByAutor1, Korisnik korisnikByAutor2, Sesija sesija, String naslov, Integer trajanje, String tip, Date pocetak, Set komentars) {
       this.korisnikByAutor3 = korisnikByAutor3;
       this.korisnikByAutor4 = korisnikByAutor4;
       this.korisnikByAutor1 = korisnikByAutor1;
       this.korisnikByAutor2 = korisnikByAutor2;
       this.sesija = sesija;
       this.naslov = naslov;
       this.trajanje = trajanje;
       this.tip = tip;
       this.pocetak = pocetak;
       this.komentars = komentars;
    }
   
    public Integer getIdpred() {
        return this.idpred;
    }
    
    public void setIdpred(Integer idpred) {
        this.idpred = idpred;
    }
    public Korisnik getKorisnikByAutor3() {
        return this.korisnikByAutor3;
    }
    
    public void setKorisnikByAutor3(Korisnik korisnikByAutor3) {
        this.korisnikByAutor3 = korisnikByAutor3;
    }
    public Korisnik getKorisnikByAutor4() {
        return this.korisnikByAutor4;
    }
    
    public void setKorisnikByAutor4(Korisnik korisnikByAutor4) {
        this.korisnikByAutor4 = korisnikByAutor4;
    }
    public Korisnik getKorisnikByAutor1() {
        return this.korisnikByAutor1;
    }
    
    public void setKorisnikByAutor1(Korisnik korisnikByAutor1) {
        this.korisnikByAutor1 = korisnikByAutor1;
    }
    public Korisnik getKorisnikByAutor2() {
        return this.korisnikByAutor2;
    }
    
    public void setKorisnikByAutor2(Korisnik korisnikByAutor2) {
        this.korisnikByAutor2 = korisnikByAutor2;
    }
    public Sesija getSesija() {
        return this.sesija;
    }
    
    public void setSesija(Sesija sesija) {
        this.sesija = sesija;
    }
    public String getNaslov() {
        return this.naslov;
    }
    
    public void setNaslov(String naslov) {
        this.naslov = naslov;
    }
    public Integer getTrajanje() {
        return this.trajanje;
    }
    
    public void setTrajanje(Integer trajanje) {
        this.trajanje = trajanje;
    }
    public String getTip() {
        return this.tip;
    }
    
    public void setTip(String tip) {
        this.tip = tip;
    }
    public Date getPocetak() {
        return this.pocetak;
    }
    
    public void setPocetak(Date pocetak) {
        this.pocetak = pocetak;
    }
    public Set getKomentars() {
        return this.komentars;
    }
    
    public void setKomentars(Set komentars) {
        this.komentars = komentars;
    }




}


