package db;
// Generated Jul 7, 2017 7:01:22 PM by Hibernate Tools 4.3.1



/**
 * PrijavaPredavanje generated by hbm2java
 */
public class PrijavaPredavanje  implements java.io.Serializable {


     private Integer idPrijava;
     private Korisnik korisnik;
     private Sesija sesija;

    public PrijavaPredavanje() {
    }

    public PrijavaPredavanje(Korisnik korisnik, Sesija sesija) {
       this.korisnik = korisnik;
       this.sesija = sesija;
    }
   
    public Integer getIdPrijava() {
        return this.idPrijava;
    }
    
    public void setIdPrijava(Integer idPrijava) {
        this.idPrijava = idPrijava;
    }
    public Korisnik getKorisnik() {
        return this.korisnik;
    }
    
    public void setKorisnik(Korisnik korisnik) {
        this.korisnik = korisnik;
    }
    public Sesija getSesija() {
        return this.sesija;
    }
    
    public void setSesija(Sesija sesija) {
        this.sesija = sesija;
    }




}


