package db;
// Generated Jul 7, 2017 7:01:22 PM by Hibernate Tools 4.3.1



/**
 * Prijava generated by hbm2java
 */
public class Prijava  implements java.io.Serializable {


     private Integer idPrijava;
     private Konferencija konferencija;
     private Korisnik korisnik;

    public Prijava() {
    }

    public Prijava(Konferencija konferencija, Korisnik korisnik) {
       this.konferencija = konferencija;
       this.korisnik = korisnik;
    }
   
    public Integer getIdPrijava() {
        return this.idPrijava;
    }
    
    public void setIdPrijava(Integer idPrijava) {
        this.idPrijava = idPrijava;
    }
    public Konferencija getKonferencija() {
        return this.konferencija;
    }
    
    public void setKonferencija(Konferencija konferencija) {
        this.konferencija = konferencija;
    }
    public Korisnik getKorisnik() {
        return this.korisnik;
    }
    
    public void setKorisnik(Korisnik korisnik) {
        this.korisnik = korisnik;
    }




}


