package db;
// Generated Jul 7, 2017 7:01:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sala generated by hbm2java
 */
public class Sala  implements java.io.Serializable {


     private Integer idsala;
     private Mesto mesto;
     private String naziv;
     private Set sesijas = new HashSet(0);

    public Sala() {
    }

	
    public Sala(Mesto mesto, String naziv) {
        this.mesto = mesto;
        this.naziv = naziv;
    }
    public Sala(Mesto mesto, String naziv, Set sesijas) {
       this.mesto = mesto;
       this.naziv = naziv;
       this.sesijas = sesijas;
    }
   
    public Integer getIdsala() {
        return this.idsala;
    }
    
    public void setIdsala(Integer idsala) {
        this.idsala = idsala;
    }
    public Mesto getMesto() {
        return this.mesto;
    }
    
    public void setMesto(Mesto mesto) {
        this.mesto = mesto;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public Set getSesijas() {
        return this.sesijas;
    }
    
    public void setSesijas(Set sesijas) {
        this.sesijas = sesijas;
    }




}


