package db;
// Generated Jul 7, 2017 7:01:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sesija generated by hbm2java
 */
public class Sesija  implements java.io.Serializable {


     private Integer idsesija;
     private Konferencija konferencija;
     private Sala sala;
     private Date datum;
     private Set galerijas = new HashSet(0);
     private Set predavanjes = new HashSet(0);
     private Set prijavaPredavanjes = new HashSet(0);

    public Sesija() {
    }

	
    public Sesija(Konferencija konferencija) {
        this.konferencija = konferencija;
    }
    public Sesija(Konferencija konferencija, Sala sala, Date datum, Set galerijas, Set predavanjes, Set prijavaPredavanjes) {
       this.konferencija = konferencija;
       this.sala = sala;
       this.datum = datum;
       this.galerijas = galerijas;
       this.predavanjes = predavanjes;
       this.prijavaPredavanjes = prijavaPredavanjes;
    }
   
    public Integer getIdsesija() {
        return this.idsesija;
    }
    
    public void setIdsesija(Integer idsesija) {
        this.idsesija = idsesija;
    }
    public Konferencija getKonferencija() {
        return this.konferencija;
    }
    
    public void setKonferencija(Konferencija konferencija) {
        this.konferencija = konferencija;
    }
    public Sala getSala() {
        return this.sala;
    }
    
    public void setSala(Sala sala) {
        this.sala = sala;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }
    public Set getGalerijas() {
        return this.galerijas;
    }
    
    public void setGalerijas(Set galerijas) {
        this.galerijas = galerijas;
    }
    public Set getPredavanjes() {
        return this.predavanjes;
    }
    
    public void setPredavanjes(Set predavanjes) {
        this.predavanjes = predavanjes;
    }
    public Set getPrijavaPredavanjes() {
        return this.prijavaPredavanjes;
    }
    
    public void setPrijavaPredavanjes(Set prijavaPredavanjes) {
        this.prijavaPredavanjes = prijavaPredavanjes;
    }




}


